const pt_br: Strings = {
  appName: "Monopix",
  appIntro1: "Olá ",
  appIntro2:
    " Estamos felizes em tê-lo(a) no Monopix App. Prepare-se para vivenciar a emoção de negociações, estratégias e vitórias no mundo imobiliário. Divirta-se!",
  continue: "Continuar",
  hello: "Olá, ",
  lobby: "Saguão",
  players: "Jogadores",
  waitingForPlayer: "Aguardando Jogador",
  leaveLobby: "Sair do saguão",
  startGame: "Iniciar Jogo",
  qrCodeHint:
    "Para entrar no lobby, escaneie o QR Code acima com o aplicativo do Monopoly. Junte-se aos jogadores e prepare-se para a diversão!",
  balance: "Saldo",
  charge: "Cobrar",
  deposit: "Depositar",
  pay: "Pagar",
  transfer: "Transferir",
  history: "Histórico",
  scoreboard: "Placar",
  myProperties: "Minhas Propriedades",
  cancel: "Cancelar",
  confirm: "Confirmar",
  depositSuccess: "Deposito realizado com sucesso",
  digitValue: "Digite o valor",
  makeDeposit: "Realizar Depósito",
  bank: "Banco",
  makeTransfer: "Realizar Transferência",
  transferSuccess: "Trasnferência realizada com successo",
  transferReceived: "Transferência recebida no valor de: ",
  wantsToReceive: "deseja receber",
  gameNotFound: "Jogo não encontrado em nossa base de dados",
  goBack: "Voltar",
  opsGameNotFound:
    "Ops... parece que não consiguimos encontrar o jogo que procura em nosso banco de dados",
  close: "Fechar",
  extract: "Extrato",
  destiny: "Destino",
  edit: "Editar",
  mortgage: "Hipoteca",
  rent: "Aluguel",
  addProperty: "Adicionar Propriedade",
  remove: "Remover",
  continueLastGame: "Continuar última partida",
  createGame: "Criar Partida",
  joinGame: "Entrar em partida",
  welcome: "Bem-vindo ao Monopix App!",
  whereToGo: "O que deseja fazer hoje?",
  //Errors
  retriveUserDataError:
    "Ocorreu um problema ao carregar informações do usuário",
  saveUserDataError: "Ocorreu um problema ao salvar informações do usuário",
  fieldMustBeFilled: "O campo precisa ser preenchido",
  failedToRetriveGameData: "Falha ao recuperar dados do jogo",
  failedToRetriveUserData: "Falha ao recuperar dados do usuário",
  gameIsFull: "O jogo já chegou ao seu limite de jogadores",
  failedToStartGame: "Falha ao iniciar jogo",
  failedToTransferMoney: "Falha ao realizar transação",
  insuficientBalance: "Saldo insuficiente",
  valueCantBeZero: "Valor não pode ser zero",
  invalidQrCode: "Código escaneado não é válido",
  mortgageCantBeZero: "O valor da hipoteca não pode ser zero",
  rentCantBeZero: "O valor do aluguel não pode ser zero",
  nameCantBeUndefined: "O nome precisa ser preenchido",
  failedToAddProperty: "Falha ao adicionar propriedade",
  failedToRemoveProperty: "Falha ao remover propriedade",
  failedToUpdateProperty: "Falha ao atualizar propriedade",
};

export default pt_br;
