const pt_br: Strings = {
  appName: 'PixPlay',
  appIntro1: 'Olá ',
  appIntro2:
    ' Estamos felizes em tê-lo(a) no PixPlay App. Prepare-se para vivenciar a emoção de negociações, estratégias e vitórias no mundo imobiliário. Divirta-se!',
  continue: 'Continuar',
  hello: 'Olá, ',
  lobby: 'Saguão',
  players: 'Jogadores',
  waitingForPlayer: 'Aguardando Jogador',
  leaveLobby: 'Sair do saguão',
  startGame: 'Iniciar Jogo',
  qrCodeHint:
    'Para entrar no lobby, escaneie o QR Code acima com o aplicativo do PixPlay. Junte-se aos jogadores e prepare-se para a diversão!',
  balance: 'Saldo',
  charge: 'Cobrar',
  deposit: 'Depositar',
  pay: 'Pagar',
  transfer: 'Transferir',
  history: 'Histórico',
  scoreboard: 'Placar',
  myProperties: 'Minhas Propriedades',
  cancel: 'Cancelar',
  confirm: 'Confirmar',
  depositSuccess: 'Deposito realizado com sucesso',
  digitValue: 'Digite o valor',
  makeDeposit: 'Realizar Depósito',
  bank: 'Banco',
  makeTransfer: 'Realizar Transferência',
  transferSuccess: 'Trasnferência realizada com successo',
  transferReceived: 'Transferência recebida no valor de: ',
  wantsToReceive: 'deseja receber',
  gameNotFound: 'Jogo não encontrado em nossa base de dados',
  goBack: 'Voltar',
  opsGameNotFound:
    'Ops... parece que não consiguimos encontrar o jogo que procura em nosso banco de dados',
  close: 'Fechar',
  extract: 'Extrato',
  destiny: 'Destino',
  edit: 'Editar',
  mortgage: 'Hipoteca',
  rent: 'Aluguel',
  addProperty: 'Adicionar Propriedade',
  remove: 'Remover',
  continueLastGame: 'Continuar última partida',
  createGame: 'Criar Partida',
  joinGame: 'Entrar em partida',
  welcome: 'Bem-vindo ao PixPlay App!',
  whereToGo: 'O que deseja fazer hoje?',
  starterValueHelp:
    'Informe o valor inicial com que os jogadores começarão o jogo',
  options: 'Opções',
  changeName: 'Alterar Nome',
  changeColor: 'Alterar Cor',
  shareApp: 'Compartilhar App',
  howItWorks: 'Como Usar',
  developerInfo: 'Desenvolvedor',
  shareText: 'Baixe o PixPlay para começar a se divertir com seus amigos!',
  shareGameHelp:
    'Caso algum participante tenha perdido a conexão com o jogo, ele pode voltar ao escanear o QR code acima',
  fastCharge: 'Cobrança Rápida',
  newItem: 'Novo Item',
  value: 'Valor',
  editItem: 'Editar Item',
  //how to use
  usesRealMoney: 'O dinheiro utilizado é real?',
  usesRealMoneyRes:
    'Não, o aplicativo PixPay não utiliza dinheiro real. Todo o dinheiro presente no aplicativo é fictício e serve exclusivamente para os propósitos do jogo. O PixPay é projetado para substituir as cédulas em jogos de tabuleiro, permitindo que os jogadores realizem transferências dentro do contexto do jogo, sem qualquer valor monetário real aplicado a elas. Portanto, você pode desfrutar do jogo de tabuleiro sem se preocupar com o uso de dinheiro real.',
  howToCreateGame: 'Como criar uma partida?',
  howToCreateGameRes:
    'Para criar uma partida, basta apertar o botão "Criar Partida" na tela principal do aplicativo. Você será redirecionado(a) para o lobby do jogo, onde será exibido um código QR que seus amigos poderão escanear para se juntar à partida. Ao iniciar a partida, uma caixa de diálogo aparecerá, solicitando que você informe o valor inicial de dinheiro com o qual os jogadores começarão a partida. Por padrão, esse valor é definido como 15 milhões. No entanto, você pode personalizá-lo de acordo com as preferências do grupo. Lembre-se de que é necessário ter pelo menos 2 jogadores para iniciar a partida, e apenas o líder do lobby terá a permissão para iniciar quando estiverem prontos.',
  howToJoinGame: 'Como entrar em uma partida?',
  howToJoinGameRes:
    'Para entrar em uma partida, basta apertar o botão "Entrar em uma Partida" na tela principal do aplicativo. Ao fazer isso, a câmera será aberta, e você deverá escanear o QR code fornecido pelo líder da partida. Após escanear o QR code, você será direcionado(a) para a sala da partida e poderá aguardar o líder iniciar o jogo.',
  canIJoinAStartedGame: 'Posso me juntar a um jogo em andamento?',
  canIJoinAStartedGameRes:
    'Após o líder iniciar o jogo, não é mais possível se juntar àquela partida em andamento. É importante lembrar que o processo de entrada em uma partida deve ser concluído antes que o líder dê início ao jogo. Portanto, certifique-se de se juntar a uma partida antes que o líder inicie, escaneando o QR code fornecido pelo líder durante a fase de preparação. Dessa forma, você poderá participar do jogo desde o início e aproveitar a experiência completa com os demais jogadores.',
  canIRejoinTheGame: 'Perdi conexão, posso voltar ao jogo?',
  canIRejoinTheGameRes:
    'Sim, se você perdeu a conexão durante o jogo, ainda é possível voltar. Na tela do jogo, você encontrará um botão no canto superior direito que abre um QR code. Basta escanear esse QR code utilizando o seu dispositivo para se reconectar à partida em andamento. Ao fazer isso, você será capaz de retomar a sua posição no jogo e continuar jogando com os outros participantes. Certifique-se de ter uma conexão estável à internet para evitar interrupções durante o jogo.',
  //Errors
  retriveUserDataError:
    'Ocorreu um problema ao carregar informações do usuário',
  saveUserDataError: 'Ocorreu um problema ao salvar informações do usuário',
  fieldMustBeFilled: 'O campo precisa ser preenchido',
  failedToRetriveGameData: 'Falha ao recuperar dados do jogo',
  failedToRetriveUserData: 'Falha ao recuperar dados do usuário',
  gameIsFull: 'O jogo já chegou ao seu limite de jogadores',
  failedToStartGame: 'Falha ao iniciar jogo',
  failedToTransferMoney: 'Falha ao realizar transação',
  insuficientBalance: 'Saldo insuficiente',
  valueCantBeZero: 'Valor não pode ser zero',
  invalidQrCode: 'Código escaneado não é válido',
  mortgageCantBeZero: 'O valor da hipoteca não pode ser zero',
  rentCantBeZero: 'O valor do aluguel não pode ser zero',
  nameCantBeUndefined: 'O nome precisa ser preenchido',
  failedToAddProperty: 'Falha ao adicionar propriedade',
  failedToRemoveProperty: 'Falha ao remover propriedade',
  failedToUpdateProperty: 'Falha ao atualizar propriedade',
};

export default pt_br;
