name: Build Prod
on:
  push:
    branches:
      - master
jobs:
  build:
      name: Install and build
      runs-on: ubuntu-latest
      needs: checkVersion
      steps:
        - name: Setup Expo and EAS
          uses: expo/expo-github-action@v8
          with:
            eas-version: latest
            token: ${{ secrets.EXPO_TOKEN }}
            
        - name: Install dependencies
          run: npm ci
        - name: Build on EAS
          run: eas build -p android --profile production --non-interactive