name: EAS Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  checkVersion:
    name: Check package version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check package.json version
        id: package-version
        run: |
          current_version=$(node -p "require('./package.json').version")
          previous_version=$(git log -n 1 --pretty=format:%s | grep -oP "(?<=Bump version to )\d+\.\d+\.\d+")
          echo "$previous_version"
          if [[ "$current_version" == "$previous_version" || $(echo "$current_version <= $previous_version" | bc -l) -eq 1 ]]; then
            echo "Version check failed. Stopping workflow."
            exit 1
          else
            echo "Version check passed. Continuing workflow."
          fi

      - name: Check app.json expo version
        id: expo-version
        run: |
          current_version=$(node -p "require('./app.json').expo.version")
          previous_version=$(git log -n 1 --pretty=format:%s | grep -oP "(?<=Bump version to )\d+\.\d+\.\d+")
          if [[ "$current_version" == "$previous_version" || $(echo "$current_version <= $previous_version" | bc -l) -eq 1 ]]; then
            echo "Version check failed. Stopping workflow."
            exit 1
          else
            echo "Version check passed. Continuing workflow."
          fi

  build:
    name: Install and build
    runs-on: ubuntu-latest
    needs: checkVersion
    if: ${{ needs.checkVersion.outputs.package-version == 'Version check passed. Continuing workflow.' && needs.checkVersion.outputs.expo-version == 'Version check passed. Continuing workflow.' }}
    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      # - name: Install dependencies
      #   run: npm ci
      # - name: Build on EAS
      #   run: eas build -p android --profile production --non-interactive
